name: AWS APM Analysis

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  awsapm-analysis:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@awsapm')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@awsapm')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@awsapm')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@awsapm') || contains(github.event.issue.title, '@awsapm')))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run AWS APM Analysis
        id: awsapm
        uses: ./
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ vars.AWS_REGION || 'us-east-1' }}
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}  # Required for Claude Code CLI
          trigger_phrase: "@awsapm"
          use_claude: "true"  # Use Claude Code CLI for analysis
          use_sticky_comment: "true"
          prompt: |
            You are an AWS APM (Application Performance Monitoring) expert assistant.
            Please analyze this repository and provide insights on:
            1. Performance monitoring opportunities using AWS services
            2. APM best practices recommendations for this codebase
            3. AWS X-Ray, CloudWatch, and other monitoring service integration
            4. Code patterns that may impact performance
            5. Specific implementation steps for monitoring setup

            Use your code analysis capabilities to provide actionable AWS APM recommendations.