name: AWS APM Investigation

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  awsapm-investigation:
    if: |
      (github.event_name == 'issue_comment' && (contains(github.event.comment.body, '@awsapm') || contains(github.event.comment.body, '@aws-apm'))) ||
      (github.event_name == 'pull_request_review_comment' && (contains(github.event.comment.body, '@awsapm') || contains(github.event.comment.body, '@aws-apm'))) ||
      (github.event_name == 'pull_request_review' && (contains(github.event.review.body, '@awsapm') || contains(github.event.review.body, '@aws-apm'))) ||
      (github.event_name == 'issues' && ((contains(github.event.issue.body, '@awsapm') || contains(github.event.issue.body, '@aws-apm')) || (contains(github.event.issue.title, '@awsapm') || contains(github.event.issue.title, '@aws-apm'))))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run AWS APM Investigation
        id: awsapm
        uses: ./
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ vars.AWS_REGION || 'us-east-1' }}
          github_app_id: ${{ secrets.AWS_APM_GITHUB_APP_ID }}  # For custom bot name
          github_app_private_key: ${{ secrets.AWS_APM_GITHUB_APP_PRIVATE_KEY }}  # For custom bot name
          trigger_phrase: "@awsapm"
          use_sticky_comment: "true"
          enable_cloudwatch_mcp: "true"  # Enable CloudWatch MCP tools
