name: Integration Test

on:
  schedule:
    - cron: '0 */6 * * *'
  push:
    branches:
      - zhaez/integ-test

jobs:
  awsapm-investigation:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Application observability for AWS Investigation
        id: awsapm
        uses: ./
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ vars.AWS_REGION || 'us-east-1' }}
          bot_name: "@awsapm"
          enable_cloudwatch_mcp: "true"  # Enable CloudWatch Application Signals MCP
          tracing_mode: "true"  # Show AI agent reasoning steps
          test_mode: "true"  # Enable integration test mode
          custom_prompt: "Which of my services are currently actively running on CloudWatch?"

      - name: Upload test outputs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-outputs
          path: |
            ${{ runner.temp }}/awsapm-output/
            ${{ runner.temp }}/awsapm-prompts/
          retention-days: 7